baseURL: /
title: "wittberger.net - Daniel Wittberger"
defaultContentLanguage: de
languages:
  de:
    lang: de
    languageName: Deutsch
    weight: 1
taxonomies:
  category: categories
  tag: tags
MetaDataFormat: "yaml"
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false
