baseURL: /
title: "wittberger.net - Daniel Wittberger"
defaultContentLanguage: de
languages:
  de:
    lang: de
    languageName: Deutsch
    weight: 1
taxonomies:
  category: categories
  tag: tags
MetaDataFormat: "yaml"
theme: "wittberger"
blackfriday:
   plainIDAnchors: true
   hrefTargetBlank: true
