name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --minify
      
      - name: rsync deploy
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -vr --delete
          path: public/
          remote_path: /var/www/wittberger.net-gh
          remote_host: vps.wittberger.net
          remote_user: webdeploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
